version: "3.1"
services:

    mysql:
      volumes:
        - ./mysql:/mysql
        - ./mysql/mysqldump:/docker-entrypoint-initdb.d
        - mysql-data:/var/lib/mysql
      image: mysql:8.0
      container_name: mysql8
      working_dir: /mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PSWD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_USER_PSWD}
        - MYSQL_PORT=3306
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      #ports:
      #  - "9002:3306"
      networks:
        - mysql-backend

networks:
  mysql-backend:

volumes:
  mysql-data:
