
###############################################################################
version: "3.1"
services:

    mysql:
      volumes:
        - ./phpdocker:/application
        - php7-4-mysql-data:/var/lib/mysql
        #- ./phpdocker/mysql-dump:/docker-entrypoint-initdb.d
      image: mysql:8.0
      container_name: php7-4-mysql
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PSWD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_USER_PSWD}
        - MYSQL_PORT=3306
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      ports:
        - "9002:3306"
      networks:
        - lemp-backend
    
    php-fpm:
      build: phpdocker/php-fpm
      container_name: php7-4-php-fpm
      working_dir: /application
      volumes:
        - ./phpdocker:/application
        - ./phpdocker/nginx/public/:/application/public/
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.in
      networks:
        - lemp-backend
   
    webserver:
      image: nginx:1.17.8-alpine
      container_name: php7-4-webserver
      working_dir: /application
      volumes:
          - ./phpdocker:/application
          - ./phpdocker/nginx/public/:/application/public/
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9000:80"
      networks:
        - lemp-backend

networks:
  lemp-backend:

volumes:
  php7-4-mysql-data:
